/**
 * ============================================================================
 * AUTHENTICATION MIDDLEWARE
 * ============================================================================
 *
 * PURPOSE: JWT token validation middleware for Gin framework
 * SCOPE: Token validation, user extraction, account ID resolution
 *
 * This middleware validates JWT tokens generated by screenjournal-backend.
 * It does NOT generate tokens - only validates them.
 *
 * Based on screenjournal-backend/src/api/middleware/auth.ts
 *
 * ============================================================================
 */

package middleware

import (
	"fmt"
	"net/http"
	"os"
	"strconv"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/golang-jwt/jwt/v5"
)

// TokenClaims represents the JWT token payload structure
// Matches the structure from screenjournal-backend (userId, email, iat, exp)
type TokenClaims struct {
	UserId string `json:"userId"`
	Email  string `json:"email"`
	jwt.RegisteredClaims
}

// AuthContext represents user information extracted from the token
type AuthContext struct {
	UserID    int
	Email     string
	AccountID int // Will be extracted from token if available, or set to 0
}

/**
 * Extract Bearer token from Authorization header
 */
func extractBearerToken(c *gin.Context) (string, error) {
	authHeader := c.GetHeader("Authorization")
	if authHeader == "" {
		return "", fmt.Errorf("authorization header missing")
	}

	if !strings.HasPrefix(authHeader, "Bearer ") {
		return "", fmt.Errorf("invalid authorization header format")
	}

	token := strings.TrimPrefix(authHeader, "Bearer ")
	if token == "" {
		return "", fmt.Errorf("token missing")
	}

	return token, nil
}

/**
 * Verify and decode JWT token
 */
func verifyToken(tokenString string) (*TokenClaims, error) {
	// Get JWT secret from environment
	jwtSecret := os.Getenv("JWT_SECRET")
	if jwtSecret == "" {
		return nil, fmt.Errorf("JWT_SECRET not configured")
	}

	// Parse and verify token
	token, err := jwt.ParseWithClaims(tokenString, &TokenClaims{}, func(token *jwt.Token) (interface{}, error) {
		// Validate signing method
		if _, ok := token.Method.(*jwt.SigningMethodHMAC); !ok {
			return nil, fmt.Errorf("unexpected signing method: %v", token.Header["alg"])
		}
		return []byte(jwtSecret), nil
	})

	if err != nil {
		// Check for specific error types
		if err == jwt.ErrTokenExpired {
			return nil, fmt.Errorf("token expired")
		}
		if err == jwt.ErrTokenMalformed {
			return nil, fmt.Errorf("malformed token")
		}
		return nil, fmt.Errorf("invalid token: %w", err)
	}

	// Extract claims
	if claims, ok := token.Claims.(*TokenClaims); ok && token.Valid {
		return claims, nil
	}

	return nil, fmt.Errorf("invalid token claims")
}

/**
 * Extract account ID from token claims
 * Note: In screenjournal-backend, account_id is stored in the user object, not the token.
 * For now, we'll return 0 if account_id is not in the token.
 * This can be extended if needed.
 */
func extractAccountID(claims *TokenClaims) int {
	// If account_id is in the token claims, extract it
	// Otherwise, return 0 (will need to be set from user lookup if needed)
	return 0
}

/**
 * AuthenticateUser is the main authentication middleware
 * It validates JWT tokens and attaches user info to the request context
 */
func AuthenticateUser() gin.HandlerFunc {
	return func(c *gin.Context) {
		// Extract token
		token, err := extractBearerToken(c)
		if err != nil {
			c.JSON(http.StatusUnauthorized, gin.H{
				"error":   "Unauthorized",
				"message": "Invalid or expired token",
			})
			c.Abort()
			return
		}

		// Verify token
		claims, err := verifyToken(token)
		if err != nil {
			c.JSON(http.StatusUnauthorized, gin.H{
				"error":   "Unauthorized",
				"message": err.Error(),
			})
			c.Abort()
			return
		}

		// Extract user ID from claims
		userID, err := strconv.Atoi(claims.UserId)
		if err != nil {
			c.JSON(http.StatusUnauthorized, gin.H{
				"error":   "Unauthorized",
				"message": "Invalid user ID in token",
			})
			c.Abort()
			return
		}

		// Create auth context
		authContext := AuthContext{
			UserID:    userID,
			Email:     claims.Email,
			AccountID: extractAccountID(claims),
		}

		// Attach to context
		c.Set("user", authContext)
		c.Set("userId", userID)
		c.Set("email", claims.Email)
		c.Set("accountId", authContext.AccountID)

		c.Next()
	}
}

/**
 * RequireAuth is a simpler middleware that only validates the token
 * without attaching user info to the request
 */
func RequireAuth() gin.HandlerFunc {
	return func(c *gin.Context) {
		// Extract token
		token, err := extractBearerToken(c)
		if err != nil {
			c.JSON(http.StatusUnauthorized, gin.H{
				"error":   "Unauthorized",
				"message": "Invalid or expired token",
			})
			c.Abort()
			return
		}

		// Verify token
		_, err = verifyToken(token)
		if err != nil {
			c.JSON(http.StatusUnauthorized, gin.H{
				"error":   "Unauthorized",
				"message": err.Error(),
			})
			c.Abort()
			return
		}

		c.Next()
	}
}

/**
 * GetAuthContext extracts the auth context from the Gin context
 * Returns nil if not authenticated
 */
func GetAuthContext(c *gin.Context) *AuthContext {
	user, exists := c.Get("user")
	if !exists {
		return nil
	}

	authContext, ok := user.(AuthContext)
	if !ok {
		return nil
	}

	return &authContext
}

